# Generated by Django 4.2 on 2023-05-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0006_delete_pressure_delete_temperature_device_mac'),
        ('Measurements', '0002_measurement_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Device.device'),
        ),
    ]
