# Generated by Django 4.2 on 2023-05-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0003_alter_log_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='device',
        ),
    ]
