# Generated by Django 4.2 on 2023-05-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='usr',
            new_name='user',
        ),
    ]
