# Generated by Django 4.2 on 2023-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_rename_bio_profile_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
    ]
