# Generated by Django 4.2 on 2023-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0007_alter_schedule_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'red'), ('bg-warning', 'yellow'), ('bg-info', 'azure'), ('bg-success', 'green'), ('bg-primary', 'blue'), ('bg-secondary', 'gray'), ('bg-dark', 'dark gray')], default='bg-danger', max_length=20),
        ),
    ]
