# Generated by Django 4.2 on 2023-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0009_alter_schedule_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('CEO', 'Product Owner'), ('HWE', 'Hardware Engineer'), ('SWE', 'Software Engineer'), ('MCE', 'Mechanical Engineer'), ('BIO', 'Biomedical Engineer'), ('NSE', 'Network Software Engineer'), ('HSE', 'Hardware / Software Engineer'), ('NBS', 'Nobody Special')], default='NBS', max_length=50),
        ),
    ]
