# Generated by Django 4.2 on 2023-05-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0002_alter_publication_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(unique=True, upload_to='Publications/'),
        ),
    ]
