# Generated by Django 4.2 on 2023-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_url', models.BooleanField()),
                ('title', models.CharField(default='', max_length=20)),
                ('file', models.FileField(null=True, unique=True, upload_to='Sources/')),
                ('slug', models.SlugField(default='', unique=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
