# Generated by Django 4.2 on 2023-05-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sources', '0003_alter_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='is_from_url',
        ),
    ]
