# Generated by Django 4.2 on 2023-05-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sources', '0004_remove_source_is_from_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Sources/'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
