# Generated by Django 4.2 on 2023-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sources', '0005_alter_source_file_alter_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='character',
            field=models.CharField(choices=[('PUB', 'Publication'), ('OTH', 'Other')], default='PUB', max_length=3),
        ),
    ]
